version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: UE9TVEdSRVNfUEFTU1dPUkQ=
      POSTGRES_USER: postgres
      POSTGRES_DB: keyiu
    volumes:
      - ~/data/keyiu:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
